### PR TITLE
My pull request for your consideration.

### PR DESCRIPTION
**Pull request by OliveiraEdu**
Hi Remche,

I hope this finds you well.

Allow me to send you this draft pull request, I hope this can be useful for someone else.

I just would like to thank you for your work on the yade docker container, I'm using the updated version for the Methods for Discrete Elements course on my masters.

Best Regards,

Eduardo

### CODE REVIEW

**Comment by remche** [comment]
Hey @OliveiraEdu,
Thanks for your work. I did not work on that since a long time... I will rename the repository to be more version generic and we can go ahead with that MR.

**Comment by remche** [comment]
I just did small changes. We could think about an automatic build if it makes sense.

**Comment by remche** [comment]
@OliveiraEdu is this PR ready for merge ?

**Comment by OliveiraEdu** [comment]
@remche the PR is good to go, thank you.

**Comment by OliveiraEdu** [comment]
@remche the PR is good to go, thank you.

**Pull request merged**
